dist: xenial # Ubuntu 16.04

language: bash

env:
  - tf_version=0.12.24 tf_workdir_example1="examples/golang-hello-world-webapp-ec2" tf_workdir_example2="examples/golang-hello-world-webapp-fargate"

# Only build pushes to master branch
branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip


# Terraform Commands
jobs:
  include:
    - stage: terraform plan ec2 example
      script:
        - echo "Executing Terraform ec2 example plan"
        - terraform -version
        - terraform init $tf_workdir_example1
        - terraform validate $tf_workdir_example1
        - terraform plan $tf_workdir_example1
    - stage: terraform plan ecs fargate example
      script:
        - echo "Executing Terraform fargate plan"
        - terraform -version
        - terraform init $tf_workdir_example2
        - terraform validate $tf_workdir_example2
        - terraform plan $tf_workdir_example2