dist: xenial # Ubuntu 16.04

language: bash

env:
  - tf_version=0.12.24 tf_workdir="examples/golang-hello-world-webapp"

# Only build pushes to master branch
branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip


# Terraform Commands
jobs:
  include:
    - stage: terraform plan
      script:
        - echo "Executing Terraform Plan"
        - terraform -version
        - terraform init $tf_workdir
        - terraform validate $tf_workdir
        - terraform plan $tf_workdir